esphome:
  name: laborplatte
  friendly_name: Laborplatte

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXX"

ota:
  - platform: esphome
    password: "XXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Laborplatte Fallback Hotspot"
    password: "XXXX"

captive_portal:

i2c:
  - id: bus_a
    sda: 15
    scl: 16
    scan: true

# TCA9548A Multiplexer
tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: bus_a
    channels:
      - bus_id: multiplex0channel0
        channel: 0
      - bus_id: multiplex0channel1
        channel: 1
      - bus_id: multiplex0channel2
        channel: 2
      - bus_id: multiplex0channel3
        channel: 3


sensor:
# BME680 - Air Quality Sensor (Channel 0, Address 0x77)
  - platform: bme680
    temperature:
      name: "Temperature Channel 0"
      id: bme680_temperature
    humidity:
      name: "Humidity Channel 0"
      id: bme680_humidity
    pressure:
      name: "Pressure Channel 0"
      id: bme680_pressure
    gas_resistance:
      name: "Gas Resistance Channel 0"
      id: bme680_gas_resistance
    address: 0x77
    i2c_id: multiplex0channel0
  # advanced configuration
  - platform: template
    name: "BME680 Indoor Air Quality"
    id: iaq
    icon: "mdi:gauge"
    # calculation: comp_gas = log(R_gas[ohm]) + 0.04 log(Ohm)/%rh * hum[%rh]
    lambda: |-
      return log(id(bme680_gas_resistance).state) + 0.04 *  id(bme680_humidity).state;
    state_class: "measurement"


# SGP40 - VOC Sensor (Channel 0, Address 0x59)
  - platform: sgp4x
    voc:
      name: "VOC Index"
      id: sgp40_voc
    compensation:
      humidity_source: bme680_humidity
      temperature_source: bme680_temperature
    i2c_id: multiplex0channel0

# SCD41 - CO2 Sensor (Channel 0, Address 0x62)
  - platform: scd4x
    temperature:
      name: "CO2 Sensor Temperature"
    humidity:
      name: "CO2 Sensor Humidity"
    co2:
      name: "CO2 Concentration"
      id: co2_sensor
    address: 0x62
    i2c_id: multiplex0channel0

  # TSL2591 - Ambient Light Sensor (Channel 0, Address 0x29)
  - platform: tsl2591
    address: 0x29
    i2c_id: multiplex0channel0
    name: "Ambient Light Channel 0"
    update_interval: 60s
    gain: auto
    device_factor: 53
    glass_attenuation_factor: 14.4
    visible:
      name: "TSL2591 visible light"
    infrared:
      name: "TSL2591 infrared light"
    full_spectrum:
      name: "TSL2591 full spectrum light"
    calculated_lux:
      id: i_lux
      name: "TSL2591 Lux"
    actual_gain:
      id: "actual_gain"
      name: "TSL2591 actual gain"

  # Light and Proximity Sensors
  - platform: apds9960
    type: CLEAR
    name: "APDS9960 Clear Channel"
  - platform: apds9960
    type: RED
    name: "APDS9960 Red Channel"
  - platform: apds9960
    type: GREEN
    name: "APDS9960 Green Channel"
  - platform: apds9960
    type: BLUE
    name: "APDS9960 Blue Channel"
  - platform: apds9960
    type: PROXIMITY
    name: "APDS9960 Proximity"


# text sensor for advanced configuration of the bme680 sensor
text_sensor:
  - platform: template
    name: "BME680 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if (int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) <= 500) {
        return {"Extremely polluted"};
      }
      else {
        return {"unknown"};
      }

# MPR121 Component Capacitive Touch Sensor
# MPR121 Component
mpr121:
  id: mpr121_component
  address: 0x5A
  i2c_id: multiplex0channel0  # Link to the TCA9548A Channel 0
  touch_debounce: 1
  release_debounce: 1
  touch_threshold: 10
  release_threshold: 7

# Binary Sensors for MPR121 Channels
binary_sensor:
  - platform: mpr121
    id: touch_key0
    channel: 0
    name: "Touch Key 0"
    touch_threshold: 12
    release_threshold: 6

  - platform: mpr121
    id: touch_key1
    channel: 1
    name: "Touch Key 1"

  - platform: mpr121
    id: touch_key2
    channel: 2
    name: "Touch Key 2"

  - platform: mpr121
    id: touch_key3
    channel: 3
    name: "Touch Key 3"

  - platform: mpr121
    id: touch_key4
    channel: 4
    name: "Touch Key 4"

  - platform: mpr121
    id: touch_key5
    channel: 5
    name: "Touch Key 5"

  - platform: mpr121
    id: touch_key6
    channel: 6
    name: "Touch Key 6"
    on_press:
      then:
        - display.page.show_next: device_display
        - component.update: device_display

  - platform: mpr121
    id: touch_key7
    channel: 7
    name: "Touch Key 7"

  - platform: mpr121
    id: touch_key8
    channel: 8
    name: "Touch Key 8"

  - platform: mpr121
    id: touch_key9
    channel: 9
    name: "Touch Key 9"

  - platform: mpr121
    id: touch_key10
    channel: 10
    name: "Touch Key 10"

  - platform: mpr121
    id: touch_key11
    channel: 11
    name: "Touch Key 11"

# Gesture Detection
  - platform: apds9960
    direction: UP
    name: "APDS9960 Gesture Up"
  - platform: apds9960
    direction: DOWN
    name: "APDS9960 Gesture Down"
  - platform: apds9960
    direction: LEFT
    name: "APDS9960 Gesture Left"
  - platform: apds9960
    direction: RIGHT
    name: "APDS9960 Gesture Right"

# APDS9960 Sensor Component
apds9960:
  id: apds9960_component
  address: 0x39
  i2c_id: multiplex0channel0
  update_interval: 20s
  led_drive: 100mA
  proximity_gain: 4x
  ambient_light_gain: 16x
  gesture_led_drive: 100mA
  gesture_gain: 4x
  gesture_wait_time: 2.8ms



# Define Font
font:
  - file: "https://github.com/IdreesInc/Monocraft/releases/download/v3.0/Monocraft.ttf"
    id: web_font
    size: 9
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: roboto_16
    size: 16

# Display: SH1107 128x64-oled
# Address: 0x3c 
display:
  - platform: ssd1306_i2c
    i2c_id: bus_a
    address: 0x3c
    id: device_display
    update_interval: 10s
    rotation: 270
    offset_y: 96
    model: "SH1107 128x64"
    pages:
      - id: page1
        lambda: |-
          // Page 1: Temperature, Humidity, Pressure, Gas Resistance
          it.printf(0, 0, id(web_font), "Temp: %.1f C", id(bme680_temperature).state);
          it.printf(0, 18, id(web_font), "Humidity: %.1f %%", id(bme680_humidity).state);
          it.printf(0, 38, id(web_font), "Pressure: %.1f hPa", id(bme680_pressure).state);
          it.printf(0, 50, id(web_font), "Gas: %.0f Ohm", id(bme680_gas_resistance).state);
      - id: page2
        lambda: |-
          // Page 2: VOC Index and CO2 Levels
          it.printf(0, 0, id(roboto_16), "VOC Index: %.1f", id(sgp40_voc).state);
          it.printf(0, 20, id(roboto_16), "CO2: %.1f ppm", id(co2_sensor).state);