esphome:
  name: laborplatte
  friendly_name: Laborplatte

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXX"

ota:
  - platform: esphome
    password: "XXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Laborplatte Fallback Hotspot"
    password: "XXXX"

captive_portal:

i2c:
  - id: bus_a
    sda: 15
    scl: 16
    scan: true

tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: bus_a
    channels:
      - bus_id: multiplex0channel0
        channel: 0
      - bus_id: multiplex0channel1
        channel: 1
      - bus_id: multiplex0channel2
        channel: 2
      - bus_id: multiplex0channel3
        channel: 3

sensor:
  - platform: bme680
    temperature:
      name: "Temperature Channel 0"
    humidity:
      name: "Humidity Channel 0"
    pressure:
      name: "Pressure Channel 0"
    gas_resistance:
      name: "Gas Resistance Channel 0"
    address: 0x77
    i2c_id: multiplex0channel0
